package abalone.gameEnum;

public enum STATE {
    LAYOUT_SELECT,
    GAME,
    PASUSE,
    TIME_SETTING,
    MODE_SETTING,
    TEAM_SETTING_PVP,
    TEAM_SETTING_PVC,
    TEAM_SETTING_CVC,
    TURN_LIMIT_SETTING,
    FILE_INPUT,
    PAUSE
}
